### ISSUE TITLE
Repository is required?

### ISSUE THREAD

**Issue by bigoals365** [mmanela/PsVsts#1]
Push-ToVso -Project Iaas_TFS -Account Bigoals365.visualstudio.com -Repository MVC_Example1

Is repository the name of my local repo?

The error I get is:

Push-ToVso : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Push-ToVso -Project Iaas_TFS -Account Bigoals365.visualstudio.com
-Repository MV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (:) [Push-ToVso], RuntimeExcep
   tion
    + FullyQualifiedErrorId : InvokeMethodOnNull,Push-ToVso


Thanks...
Richard

**Comment by mmanela** [comment]
Closing since I have not heard back
