### ISSUE TITLE
Unclear Set-VstsConfig documentation

### ISSUE THREAD

**Issue by jawn** [mmanela/PsVsts#3]
I looked at the README and output of Set-VstsConfig. 

How should the name and value be set?

> C:\WINDOWS\system32> Set-VstsConfig
> 
> cmdlet Set-VstsConfig at command pipeline position 1
> Supply values for the following parameters:
> Name: name
> Value: value
> Creating config file at C:\WINDOWS\system32\PsVsts.json

**Comment by goelhardik** [comment]
It must be used like this
```
.PARAMETER Local
Flag indicates you want to set value in a local config file.
The file will be created in the current directory if it doesn't exist.
This is the default.

.PARAMETER Global
Flag indicates you want to set value in the global config file.

.Example
Set-VstsConfig -Name Project -Value MyProject
Sets the property Project to the value MyProject in the global config

.Example
Set-VstsConfig -Name Project -Value MyProject -Local
Sets the property Project to the value MyProject in a local config
```

**Comment by jkavanagh58** [comment]
Not sure where you actually set the config items though

**Comment by mmanela** [comment]
Hi @jkavanagh58  and @jawn. All commands in PsVsts take different arguments like **Account** or **Project** or **Repository**. The set-VstsConfig helps save you from typing those over and over and instead saves the values. So if you do

```
set-vstsconfig -Global -Name Project -Value Foo
```
Then you never need to pass the -Project paramater to one of the cmdlets unless you want to override your default.. 

I hope that helps.
